baseURL: /
title: PachDocs # Displayed above the tree navigation.

enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 
theme: blocks 

staticDir: "/themes/blocks/static"

outputs: 
  home: [ "HTML", "JSON"]
  page: [ "HTML", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]

params:
  # Feature Switches #

  ## Branding features
  logos:
    nav:  "/../images/pachLogo.svg"
    footer: "/../images/footerLogo.svg"

  ## Content features
  childPages: 
    display: true # displays child pages of a section.
    grandchildren: true # displays first 7 grandchildren as buttons in the card.
  editLink: 
    display: true #  displays a link to the corresponding github file for a given page; githubUrl must be set.
    githubUrl: https://github.com/lbliii/milo/tree/pachyderm-explorations/content/  # should end with content/ 
  giscus: true # displays giscus commenting on single pages.
  heroBanner:
    single: true # displays hero section with a background image, title, description, and date on single pages.
    section: true # displays hero section [...] on section pages.
    list: true # displays hero section [...] on list pages. 
    glossary: true # displays hero section [...] on glossary pages (layout:glossary frontmatter). 
  relatedArticles: true # displays related content on page.
  seriesButton: true #  displays a "Read the <> series" button at the bottom of a page with series frontmatter.
  toc: true #  displays a table of contents in a page; can be overridden by individual page settings. (WIP)
  
  ## Release Features
  versionDropdown: true # displays a top-nav dropdown with top-level sections served as versioned documentation. 
  releaseInfo:
    latest: "2.2.x" # displays the matching content directory's sections on the home page; if blank, all directories are displayed.
    patch: "2.2.6"
  downloads:
    amd64: https://github.com/pachyderm/pachyderm/releases/download/v2.2.6/pachctl_2.2.6_amd64.deb
    darwin: https://github.com/pachyderm/pachyderm/releases/download/v2.2.6/pachctl_2.2.6_darwin_amd64.zip
    linux: https://github.com/pachyderm/pachyderm/releases/download/v2.2.6/pachctl_2.2.6_linux_amd64.tar.gz

  ## Nav features 
  navLevel: true  #  displays level-2 directory items in the file tree.
  breadcrumbs: true # displays a trail of breadcrumbs
  nextPrev: true #  displays the next and previous article available on single page.

  ## Testing Features
  defaultCss: false # displays default bulma css only without branding.

## Feature Ideas 
## 1. Create a layouts/partials/brand.css file that has hugo variables to control some css from the config.yaml file. 





sitemap:
  changeFreq: monthly 
  fileName: sitemap.xml 
  priority: 0.8 

taxonomies:
  tag: tags 
  category: categories 
  solution: solutions 
  product: products 
  series: series 

markup:
  goldmark:
    renderer:
      unsafe: true

