baseURL: /
title: PachDocs ## Displayed above the tree navigation.

enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 
theme: blocks 

staticDir: "/themes/blocks/static"

outputs: 
  home: [ "HTML", "RSS", "JSON"]
  page: [ "HTML", "RSS", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]

params:
  author: Lawrence Lane
  githubUser: lbliii
  ## Feature Switches
  navLevel: false  ## true displays level-2 directory items in the file tree.
  seriesButton: true ## true displays a "Read the <series-name> series" button at the bottom of a page with a series listed.
  toc: true ## true displays a table of contents in a page; can be overridden by individual page settings. (WIP)
  releaseInfo:
    latest: 3.0.0 





sitemap:
  changeFreq: monthly 
  fileName: sitemap.xml 
  priority: 0.8 

taxonomies:
  tag: tags 
  category: categories 
  solution: solutions 
  product: products 
  series: series 

markup:
  goldmark:
    renderer:
      unsafe: true

