baseURL: /
title: PachDocs # Displayed above the tree navigation.

enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 
theme: blocks 

staticDir: "/themes/blocks/static"

outputs: 
  home: [ "HTML", "RSS", "JSON"]
  page: [ "HTML", "RSS", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]

params:
  # Feature Switches #
  breadcrumbs: true # displays a trail of breadcrumbs
  childPages: true # displays child pages of a section.
  editLink: 
    display: true #  displays a link to the corresponding github file for a given page; githubUrl must be set.
    githubUrl: https://github.com/lbliii/milo/tree/pachyderm-explorations/content/  # should end with content/
  versionDropdown: true #  displays a top-nav dropdown with top-level sections served as versioned documentation. 
  navLevel: true  #  displays level-2 directory items in the file tree.
  logos:
    nav:  "/../images/pachLogo.svg"
    footer: "/../images/footerLogo.svg"
  seriesButton: true #  displays a "Read the <series-name> series" button at the bottom of a page with a series listed.
  nextPrev: true #  displays the next and previous article available on single page.
  toc: true #  displays a table of contents in a page; can be overridden by individual page settings. (WIP)
  relatedArticles: true # displays related content on page.
  releaseInfo:
    latest: 3.0.0 





sitemap:
  changeFreq: monthly 
  fileName: sitemap.xml 
  priority: 0.8 

taxonomies:
  tag: tags 
  category: categories 
  solution: solutions 
  product: products 
  series: series 

markup:
  goldmark:
    renderer:
      unsafe: true

