baseURL: /
title: PachDocs # Displayed above the tree navigation.

enableGitInfo: true 
enableEmoji: true 
enableRobotsTXT: true 
theme: blocks 

staticDir: "/themes/blocks/static"

outputs: 
  home: [ "HTML", "RSS", "JSON"]
  page: [ "HTML", "RSS", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]

params:
  # Feature Switches #
  githubUrl: https://github.com/lbliii/milo/tree/pachyderm-explorations/content/  # github.com/{user}/{repo}/tree/{branch}/content/
  editLink: true # true displays a link to the corresponding github file for a given page; githubUrl must be set.  
  navLevel: false  # true displays level-2 directory items in the file tree.
  logo: "/../images/pachLogo.svg"
  seriesButton: true # true displays a "Read the <series-name> series" button at the bottom of a page with a series listed.
  nextPrev: true # true displays the next and previous article available on single page.
  toc: true # true displays a table of contents in a page; can be overridden by individual page settings. (WIP)
  releaseInfo:
    latest: 3.0.0 





sitemap:
  changeFreq: monthly 
  fileName: sitemap.xml 
  priority: 0.8 

taxonomies:
  tag: tags 
  category: categories 
  solution: solutions 
  product: products 
  series: series 

markup:
  goldmark:
    renderer:
      unsafe: true

